CREATE TABLE IF NOT EXISTS users (
_uid INT(11) NOT NULL AUTO_INCREMENT,
_fp CHAR(32) DEFAULT '',
_email CHAR(128) DEFAULT '',
_login CHAR(128) DEFAULT '',
_pwd CHAR(32) DEFAULT '',
_ustate TINYINT DEFAULT 0,
_umode TINYINT DEFAULT 0,
_usubj TINYINT DEFAULT 0,
_ip BIGINT DEFAULT 0,
_rtime INT(10) DEFAULT 0,
_ltime INT(10) DEFAULT 0,
_hash CHAR(64) DEFAULT '',
_setup CHAR(255) DEFAULT '{"start":"/finance"}',
PRIMARY KEY uid (_uid),
KEY fp (_fp),
KEY email (_email),
KEY login (_login),
KEY pwd (_pwd),
KEY ustate (_ustate),
KEY umode (_umode),
KEY usubj (_subj),
KEY hash (_hash)
) ENGINE=MyISAM DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS media (
id INT(11) NOT NULL AUTO_INCREMENT,
owner_id INT(11) NOT NULL,
owner_table CHAR(32) DEFAULT 'users',
owner_field CHAR(64) DEFAULT '',
filename CHAR(128) DEFAULT '',
mime CHAR(80) DEFAULT 'application/octet-stream',
uptime INT(10) DEFAULT 0,
title CHAR(255) DEFAULT '',
ord TINYINT DEFAULT 0,
PRIMARY KEY id (id),
KEY owner_id (owner_id),
KEY owner_table (owner_table),
KEY owner_field (owner_field),
KEY title (title),
KEY uptime (uptime),
KEY ord (ord)
) ENGINE=MyISAM DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
